const fs = require('fs');

function fixLesson(file) {
  let content = fs.readFileSync(file, 'utf8');

  // We can just add the missing languages by replacing existing translations with a full set for the reading text.
  
  if (file.includes('b2-lesson-1.ts')) {
    const readingTrans = `{
      es: 'En los últimos años, la forma en que opera nuestra empresa ha tenido que evolucionar rápidamente. Comenzamos como un equipo pequeño, pero pronto nos dimos cuenta de que para sobrevivir en un mercado competitivo, es crucial adaptarse a los nuevos desafíos. El año pasado, decidimos implementar una nueva política de trabajo remoto. Al principio, hubo un flujo constante de problemas técnicos menores y a algunos empleados les resultó difícil mantener su nivel habitual de productividad.\\n\\nSin embargo, nuestro equipo demostró ser increíblemente resiliente. En lugar de darse por vencidos, trabajaron juntos para superar estos obstáculos. Para fin de año, vimos una mejora significativa en la satisfacción de los empleados. También pudimos obtener mejores herramientas de software para apoyar nuestra comunicación diaria. En última instancia, este cambio nos permitió cumplir nuestros objetivos a largo plazo mucho más rápido de lo que habíamos anticipado. Nos enseñó que aceptar el cambio, en lugar de combatirlo, es la clave para un éxito duradero.',
      ru: 'За последние несколько лет методы работы нашей компании должны были быстро эволюционировать. Мы начинали как небольшая команда, но вскоре поняли, что для выживания на конкурентном рынке крайне важно адаптироваться к новым вызовам. В прошлом году мы решили внедрить новую политику удаленной работы. Поначалу был постоянный поток мелких технических проблем, и некоторым сотрудникам было трудно поддерживать свой обычный уровень продуктивности.\\n\\nОднако наша команда оказалась невероятно стойкой. Вместо того, чтобы сдаваться, они работали вместе, чтобы преодолеть эти препятствия. К концу года мы увидели значительное улучшение удовлетворенности сотрудников. Мы также смогли получить лучшие программные инструменты для поддержки нашего ежедневного общения. В конечном итоге это изменение позволило нам достичь наших долгосрочных целей намного быстрее, чем мы предполагали изначально. Это научило нас тому, что принятие перемен, а не борьба с ними, является ключом к прочному успеху.',
      zh: '在过去的几年里，我们公司的运营方式必须迅速发展。我们最初是一个小团队，但很快我们意识到，为了在竞争激烈的市场中生存，适应新挑战是至关重要的。去年，我们决定实施一项新的远程工作政策。起初，不断出现一些小技术问题，一些员工发现很难保持通常的生产力水平。\\n\\n然而，我们的团队证明了他们有着惊人的韧性。他们没有放弃，而是齐心协力克服了这些障碍。到年底，我们看到员工满意度有了显著提高。我们还获得了更好的软件工具来支持我们的日常沟通。最终，这一改变让我们比原计划更快地实现了我们的长期目标。它教会我们，拥抱变化而不是抗拒变化，才是取得持久成功的关键。',
      fr: 'Au cours des dernières années, le mode de fonctionnement de notre entreprise a dû évoluer rapidement. Nous avons commencé comme une petite équipe, mais nous avons vite compris que pour survivre sur un marché concurrentiel, il est crucial de s\\'adapter aux nouveaux défis. L\\'année dernière, nous avons décidé de mettre en œuvre une nouvelle politique de télétravail. Au début, il y a eu un flux constant de problèmes techniques mineurs, et certains employés ont eu du mal à maintenir leur niveau de productivité habituel.\\n\\nCependant, notre équipe s\\'est avérée incroyablement résiliente. Au lieu d\\'abandonner, ils ont travaillé ensemble pour surmonter ces obstacles. À la fin de l\\'année, nous avons constaté une amélioration significative de la satisfaction des employés. Nous avons également pu obtenir de meilleurs outils logiciels pour soutenir notre communication quotidienne. En fin de compte, ce changement nous a permis d\\'atteindre nos objectifs à long terme beaucoup plus rapidement que nous ne l\\'avions prévu. Cela nous a appris qu\\'accepter le changement, plutôt que de le combattre, est la clé d\\'un succès durable.',
      de: 'In den letzten Jahren musste sich die Arbeitsweise unseres Unternehmens schnell entwickeln. Wir begannen als kleines Team, aber wir erkannten bald, dass es überlebenswichtig in einem wettbewerbsintensiven Markt ist, sich an neue Herausforderungen anzupassen. Letztes Jahr beschlossen wir, eine neue Richtlinie für Fernarbeit umzusetzen. Zunächst gab es einen ständigen Strom kleinerer technischer Probleme, und einige Mitarbeiter fanden es schwierig, ihr übliches Produktivitätsniveau aufrechtzuerhalten.\\n\\nUnser Team erwies sich jedoch als unglaublich belastbar. Anstatt aufzugeben, arbeiteten sie zusammen, um diese Hindernisse zu überwinden. Bis Ende des Jahres sahen wir eine deutliche Verbesserung der Mitarbeiterzufriedenheit. Wir konnten auch bessere Software-Tools erhalten, um unsere tägliche Kommunikation zu unterstützen. Letztendlich ermöglichte uns diese Änderung, unsere langfristigen Ziele viel schneller zu erreichen, als wir ursprünglich erwartet hatten. Es hat uns gelehrt, dass die Annahme von Veränderungen, anstatt sie zu bekämpfen, der Schlüssel zu dauerhaftem Erfolg ist.',
      tr: 'Son birkaç yılda, şirketimizin işleyiş şekli hızla gelişmek zorunda kaldı. Küçük bir ekip olarak başladık, ancak rekabetçi bir pazarda hayatta kalmak için yeni zorluklara uyum sağlamanın çok önemli olduğunu kısa sürede anladık. Geçen yıl yeni bir uzaktan çalışma politikası uygulamaya karar verdik. Başlangıçta sürekli küçük teknik sorunlar yaşandı ve bazı çalışanlar normal üretkenlik seviyelerini korumakta zorlandılar.\\n\\nAncak ekibimiz inanılmaz derecede dayanıklı olduğunu kanıtladı. Pes etmek yerine bu engellerin üstesinden gelmek için birlikte çalıştılar. Yıl sonuna gelindiğinde, çalışan memnuniyetinde önemli bir iyileşme gördük. Ayrıca günlük iletişimimizi desteklemek için daha iyi yazılım araçları elde edebildik. Sonuç olarak, bu değişiklik uzun vadeli hedeflerimize başlangıçta öngördüğümüzden çok daha hızlı ulaşmamızı sağladı. Bize değişime karşı savaşmak yerine onu kucaklamanın kalıcı başarının anahtarı olduğunu öğretti.',
      ja: '過去数年間で、当社の運営方法は急速に進化する必要がありました。私たちは小さなチームとしてスタートしましたが、競争の激しい市場で生き残るためには、新しい課題に適応することが不可欠であることにすぐに気づきました。昨年、私たちは新しいリモートワークポリシーを導入することを決定しました。最初は小さな技術的な問題が絶えず発生し、一部の従業員は通常の生産性レベルを維持するのに苦労しました。\\n\\nしかし、私たちのチームは信じられないほどの回復力があることを証明しました。彼らはあきらめるのではなく、これらの障害を克服するために協力しました。年末までに、従業員の満足度が大幅に向上したことがわかりました。また、日々のコミュニケーションをサポートするためのより優れたソフトウェアツールを入手することもできました。最終的に、この変更により、当初の予想よりもはるかに早く長期的な目標を達成することができました。それは、変化と戦うのではなく変化を受け入れることが、永続的な成功の鍵であることを私たちに教えてくれました。'
    }`;
    content = content.replace(/translations:\s*{\s*es:.*?zh:.*?'\s*}/s, `translations: ${readingTrans}`);
  }

  if (file.includes('b2-lesson-2.ts')) {
    const readingTrans = `{
      ru: 'В последние десятилетия общество стало свидетелем масштабного перехода к цифровой среде. Теперь для компаний крайне важно внедрять инновационные стратегии, чтобы оставаться актуальными. Многие старые технологии быстро устарели, уступив место более быстрым, автоматизированным системам, которые обрабатывают большие объемы данных за секунды.\\n\\nНапример, теперь мы часто проводим виртуальные встречи и получаем доступ к нашим рабочим файлам с мобильного устройства во время путешествий. Вся сеть современного бизнеса опирается на эти соединения. Однако поддержание безопасной среды сейчас важнее, чем когда-либо, поскольку конфиденциальная информация постоянно передается через глобальные платформы.\\n\\nТе, кто отказывается адаптироваться, часто остаются позади, не в силах конкурировать с организациями, которые полностью принимают технологический прогресс. Заглядывая в будущее, становится ясно, что цифровые инструменты будут только больше интегрироваться в нашу повседневную жизнь.',
      zh: '在近几十年来，社会目睹了向数字环境的大规模转变。现在，公司实施创新战略以保持相关性变得至关重要。许多旧技术迅速变得过时，取而代之的是能够在几秒钟内处理大量数据的更快、更自动化的系统。\\n\\n例如，我们现在经常在旅行时举行虚拟会议并从移动设备访问我们的工作文件。现代商业的整个网络都依赖于这些连接。然而，由于敏感信息不断在全球平台之间交换，维护安全环境变得比以往任何时候都更加重要。\\n\\n那些拒绝适应的人常常发现自己被抛在后面，无法与充分拥抱技术进步的组织竞争。展望未来，很明显数字工具只会越来越深入地融入我们的日常生活中。',
      es: 'En las últimas décadas, la sociedad ha sido testigo de un cambio masivo hacia entornos digitales. Ahora es crucial para las empresas implementar estrategias innovadoras para seguir siendo relevantes. Muchas tecnologías antiguas se han vuelto rápidamente obsoletas, reemplazadas por sistemas automatizados más rápidos que procesan grandes cantidades de datos en segundos.\\n\\nPor ejemplo, ahora tenemos reuniones virtuales con frecuencia y accedemos a nuestros archivos de trabajo desde un dispositivo móvil mientras viajamos. Toda la red de los negocios modernos depende de estas conexiones. Sin embargo, mantener un entorno seguro es más importante que nunca, ya que la información sensible se intercambia constantemente a través de plataformas globales.\\n\\nAquellos que se niegan a adaptarse a menudo se quedan atrás, incapaces de competir con organizaciones que abrazan plenamente el progreso tecnológico. A medida que miramos hacia el futuro, está claro que las herramientas digitales solo se integrarán más en nuestras rutinas diarias.',
      fr: 'Au cours des dernières décennies, la société a été témoin d\\'un changement massif vers des environnements numériques. Il est désormais crucial pour les entreprises de mettre en œuvre des stratégies innovantes pour rester pertinentes. De nombreuses technologies plus anciennes sont rapidement devenues obsolètes, remplacées par des systèmes automatisés plus rapides qui traitent de grandes quantités de données en quelques secondes.\\n\\nPar exemple, nous organisons maintenant fréquemment des réunions virtuelles et accédons à nos fichiers de travail depuis un appareil mobile en voyageant. L\\'ensemble du réseau des entreprises modernes repose sur ces connexions. Cependant, maintenir un environnement sécurisé est plus important que jamais, car des informations sensibles sont constamment échangées sur des plateformes mondiales.\\n\\nCeux qui refusent de s\\'adapter se retrouvent souvent laissés pour compte, incapables de rivaliser avec des organisations qui adoptent pleinement le progrès technologique. En regardant vers l\\'avenir, il est clair que les outils numériques ne feront que s\\'intégrer davantage à nos routines quotidiennes.',
      de: 'In den letzten Jahrzehnten hat die Gesellschaft eine massive Verlagerung hin zu digitalen Umgebungen erlebt. Es ist nun entscheidend für Unternehmen, innovative Strategien umzusetzen, um relevant zu bleiben. Viele ältere Technologien sind schnell veraltet und wurden durch schnellere, automatisierte Systeme ersetzt, die große Datenmengen in Sekunden verarbeiten.\\n\\nZum Beispiel halten wir nun häufig virtuelle Besprechungen ab und greifen auf Reisen von einem mobilen Gerät auf unsere Arbeitsdateien zu. Das gesamte Netzwerk der modernen Geschäftswelt verlässt sich auf diese Verbindungen. Die Aufrechterhaltung einer sicheren Umgebung ist jedoch wichtiger denn je, da ständig vertrauliche Informationen über globale Plattformen ausgetauscht werden.\\n\\nDiejenigen, die sich weigern, sich anzupassen, bleiben oft zurück und können nicht mit Organisationen konkurrieren, die den technologischen Fortschritt voll und ganz annehmen. Wenn wir in die Zukunft blicken, ist klar, dass digitale Werkzeuge noch mehr in unsere täglichen Routinen integriert werden.',
      tr: 'Son on yıllarda toplum dijital ortamlara doğru büyük bir değişime tanık oldu. Şirketlerin güncel kalabilmek için yenilikçi stratejiler uygulaması artık çok önemli. Birçok eski teknoloji hızla kullanımdan kalktı ve yerini saniyeler içinde büyük miktarda veriyi işleyen daha hızlı, otomatik sistemlere bıraktı.\\n\\nÖrneğin, artık sık sık sanal toplantılar yapıyor ve seyahat ederken iş dosyalarımıza bir mobil cihazdan erişiyoruz. Modern iş dünyasının tüm ağı bu bağlantılara dayanmaktadır. Ancak, hassas bilgiler sürekli olarak küresel platformlar üzerinden alınıp verildiği için güvenli bir ortamı korumak her zamankinden daha önemlidir.\\n\\nUyum sağlamayı reddedenler çoğu zaman kendilerini geride kalmış bulurlar, teknolojik ilerlemeyi tamamen kucaklayan kurumlarla rekabet edemezler. Geleceğe baktığımızda, dijital araçların günlük rutinlerimize daha fazla entegre olacağı açıktır.',
      ja: 'ここ数十年で、社会はデジタル環境への大規模な移行を目の当たりにしてきました。企業が関連性を維持するためには、革新的な戦略を実施することが現在不可欠です。多くの古い技術は急速に時代遅れになり、数秒で大量のデータを処理するより高速で自動化されたシステムに取って代わられました。\\n\\nたとえば、私たちは現在、頻繁に仮想会議を開催し、旅行中にモバイルデバイスから仕事のファイルにアクセスしています。現代のビジネスのネットワーク全体がこれらの接続に依存しています。ただし、機密情報がグローバルプラットフォーム全体で継続的に交換されるため、安全な環境を維持することがこれまで以上に重要になっています。\\n\\n適応を拒否する人々はしばしば取り残され、技術の進歩を完全に受け入れている組織と競争することができません。将来を見据えると、デジタルツールが私たちの日常生活にさらに統合されることは明らかです。'
    }`;
    content = content.replace(/translations:\s*{\s*ru:.*?ja:.*?'\s*}/s, `translations: ${readingTrans}`);
  }

  fs.writeFileSync(file, content);
}

fixLesson('src/data/b2-lesson-1.ts');
fixLesson('src/data/b2-lesson-2.ts');
