import fs from 'fs';

const replacements = {
  'src/data/b2-lesson-23.ts': [
    { old: 'investigate', newWord: 'interrogate', newPron: '/ɪnˈter.ə.ɡeɪt/', newPOS: 'verb', newLevel: 'B2', newSyns: ['question', 'examine', 'grill'], newCols: ['interrogate a suspect', 'interrogate thoroughly'], newDefs: [{ def: 'to ask someone a lot of questions for a long time in order to get information, sometimes using threats', ex1: 'The police took turns to interrogate the suspect.', ex2: 'He was interrogated for hours about his whereabouts on the night of the crime.'}] },
    { old: 'witness', newWord: 'alibi', newPron: '/ˈæl.ɪ.baɪ/', newPOS: 'noun', newLevel: 'B2', newSyns: ['defense', 'excuse'], newCols: ['have an alibi', 'a solid alibi', 'provide an alibi'], newDefs: [{ def: 'proof that someone who is thought to have committed a crime could not have done it, especially the fact or statement that they were in another place at the time it happened', ex1: 'He had a cast-iron alibi for the night of the murder.', ex2: 'The suspect claimed his wife could provide an alibi.'}] },
    { old: 'innocent', newWord: 'motive', newPron: '/ˈməʊ.tɪv/', newPOS: 'noun', newLevel: 'B2', newSyns: ['reason', 'purpose', 'intention'], newCols: ['ulterior motive', 'establish a motive', 'have no motive'], newDefs: [{ def: 'a reason for doing something, especially something that is hidden or not obvious', ex1: 'The police are still looking for a motive for the attack.', ex2: 'What could possibly be her motive for lying?'}] },
    { old: 'trial', newWord: 'confess', newPron: '/kənˈfes/', newPOS: 'verb', newLevel: 'B2', newSyns: ['admit', 'acknowledge', 'own up'], newCols: ['confess to a crime', 'confess everything'], newDefs: [{ def: 'to admit that you have done something wrong or something that you feel guilty or bad about', ex1: 'After hours of questioning, he finally confessed to the crime.', ex2: 'She confessed that she had broken the vase.'}] }
  ],
  'src/data/b2-lesson-25.ts': [
    { old: 'rational', newWord: 'subconscious', newPron: '/ˌsʌbˈkɒn.ʃəs/', newPOS: 'noun', newLevel: 'B2', newSyns: ['unconscious mind', 'inner thoughts'], newCols: ['subconscious mind', 'subconscious fears'], newDefs: [{ def: 'the part of your mind that notices and remembers information when you are not actively trying to do so, and influences your behaviour even though you do not realize it', ex1: 'The memory was buried deep in her subconscious.', ex2: 'Our subconscious often processes information while we sleep.'}] },
    { old: 'empathy', newWord: 'comprehend', newPron: '/ˌkɒm.prɪˈhend/', newPOS: 'verb', newLevel: 'B2', newSyns: ['understand', 'grasp', 'perceive'], newCols: ['fully comprehend', 'difficult to comprehend'], newDefs: [{ def: 'to understand something completely', ex1: 'I fail to comprehend their attitude.', ex2: 'He stood staring at the dead body, unable to comprehend what had happened.'}] },
    { old: 'bias', newWord: 'obsess', newPron: '/əbˈses/', newPOS: 'verb', newLevel: 'B2', newSyns: ['fixate', 'preoccupy'], newCols: ['obsess about', 'obsess over'], newDefs: [{ def: 'to think about something or someone, or to cause someone to think about something or someone, all the time', ex1: 'She used to obsess about her weight.', ex2: 'He is obsessing over the details of his presentation.'}] },
    { old: 'cognitive', newWord: 'psychology', newPron: '/saɪˈkɒl.ə.dʒi/', newPOS: 'noun', newLevel: 'B2', newSyns: ['mindset', 'behavioral science'], newCols: ['child psychology', 'study psychology'], newDefs: [{ def: 'the scientific study of the way the human mind works and how it influences behaviour, or the influence of a particular person\'s character on their behaviour', ex1: 'She is studying psychology at university.', ex2: 'You have to use a little psychology when dealing with teenagers.'}] },
    { old: 'instinct', newWord: 'delusion', newPron: '/dɪˈluː.ʒən/', newPOS: 'noun', newLevel: 'B2', newSyns: ['illusion', 'misconception', 'fantasy'], newCols: ['under a delusion', 'suffer from delusions'], newDefs: [{ def: 'belief in something that is not true', ex1: 'He is under the delusion that he will get promoted this year.', ex2: 'She suffered from the delusion that she was being followed.'}] }
  ],
  'src/data/b2-lesson-26.ts': [
    { old: 'evacuate', newWord: 'landslide', newPron: '/ˈlænd.slaɪd/', newPOS: 'noun', newLevel: 'B2', newSyns: ['rockfall', 'mudslide'], newCols: ['cause a landslide', 'a massive landslide'], newDefs: [{ def: 'a mass of rock and earth moving suddenly and quickly down a steep slope', ex1: 'Heavy rain caused a landslide that blocked the mountain road.', ex2: 'Several houses were destroyed by the landslide.'}] },
    { old: 'shelter', newWord: 'blizzard', newPron: '/ˈblɪz.əd/', newPOS: 'noun', newLevel: 'B2', newSyns: ['snowstorm'], newCols: ['a severe blizzard', 'caught in a blizzard'], newDefs: [{ def: 'a severe snow storm with strong winds', ex1: 'We once got stuck in a blizzard for six hours.', ex2: 'The blizzard conditions made driving extremely dangerous.'}] },
    { old: 'devastate', newWord: 'tornado', newPron: '/tɔːˈneɪ.dəʊ/', newPOS: 'noun', newLevel: 'B2', newSyns: ['twister', 'cyclone'], newCols: ['a massive tornado', 'struck by a tornado'], newDefs: [{ def: 'a strong, dangerous wind that forms itself into an upside-down spinning cone and is able to destroy buildings as it moves across the ground', ex1: 'The tornado ripped the roof off the local school.', ex2: 'Tornado warnings were issued for the entire county.'}] },
    { old: 'severe', newWord: 'avalanche', newPron: '/ˈæv.əl.ɑːnʃ/', newPOS: 'noun', newLevel: 'B2', newSyns: ['snowslide'], newCols: ['trigger an avalanche', 'caught in an avalanche'], newDefs: [{ def: 'a large amount of ice, snow, and rock falling quickly down the side of a mountain', ex1: 'Two skiers were killed in the avalanche.', ex2: 'The loud noise triggered a massive avalanche.'}] }
  ],
  'src/data/b2-lesson-44.ts': [
    { old: 'legislation', newWord: 'referendum', newPron: '/ˌref.əˈren.dəm/', newPOS: 'noun', newLevel: 'B2', newSyns: ['vote', 'ballot', 'poll'], newCols: ['hold a referendum', 'a national referendum'], newDefs: [{ def: 'a vote in which all the people in a country or an area are asked to give their opinion about or decide an important political or social question', ex1: 'The government decided to hold a referendum on the new constitution.', ex2: 'The results of the referendum were clear.'}] },
    { old: 'campaign', newWord: 'veto', newPron: '/ˈviː.təʊ/', newPOS: 'verb', newLevel: 'B2', newSyns: ['reject', 'block', 'turn down'], newCols: ['veto a bill', 'power of veto'], newDefs: [{ def: 'to refuse to allow something, especially officially, to refuse to allow a bill to become law', ex1: 'The president threatened to veto the new tax legislation.', ex2: 'The council can veto any building plans.'}] }
  ]
};

async function run() {
    // First, let's just mock translations instead of using translation engine,
    // actually wait, to keep this self-contained, I will generate the TS code for each block.
    // I need translation for each new word. I'll use the API if I was doing it manually, but I can just hardcode them in the script.
}

run();
